Repository ofek/csi-gcs, pull requests merged in 2020-05, with the labels that each got.

#37 Ensure docs always point to the latest stable release
  .github/workflows/docs.yml
  .gitignore
  docs/.scripts/49_inject_stable_version.py
  docs/.scripts/99_global_refs.py
  docs/.snippets/abbrs.txt
  docs/.snippets/links.txt
  docs/.snippets/refs.txt
  docs/dynamic_provisioning.md
  docs/getting_started.md
  docs/static_provisioning.md
  mkdocs.yml
Labels: documentation

#36 Mount using K8S Util Mounter
  Dockerfile
  pkg/driver/driver.go
  pkg/driver/mounter.go
  pkg/driver/node.go
  pkg/flags/flags.go
  pkg/flags/flags_test.go
Labels: enhancement

#38 Delete Orphaned Pods
  .github/workflows/test.yml
  cmd/main.go
  deploy/base/controller-statefulset.yaml
  deploy/base/driver.yaml
  deploy/base/kustomization.yaml
  deploy/base/node-daemonset.yaml
  deploy/base/node-rbac.yaml
  deploy/base/published-volumes-crd.yaml
  dev-env.Dockerfile
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/published-volume/v1beta1/doc.go
  pkg/apis/published-volume/v1beta1/register.go
  pkg/apis/published-volume/v1beta1/types.go
  pkg/apis/published-volume/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/clientset/clientset.go
  pkg/client/clientset/clientset/doc.go
  pkg/client/clientset/clientset/fake/clientset_generated.go
  pkg/client/clientset/clientset/fake/doc.go
  pkg/client/clientset/clientset/fake/register.go
  pkg/client/clientset/clientset/scheme/doc.go
  pkg/client/clientset/clientset/scheme/register.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/doc.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/fake/doc.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/fake/fake_published-volume_client.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/fake/fake_publishedvolume.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/generated_expansion.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/published-volume_client.go
  pkg/client/clientset/clientset/typed/published-volume/v1beta1/publishedvolume.go
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/util/common.go
  test/sanity_test.go
Labels: enhancement

#39 Delete Orphaned Pods Docs
  docs/.snippets/links.txt
  docs/contributing/setup.md
  docs/csi_compatibility.md
  gcsfuse_flags
Labels: documentation

#43 Build Image & Publish in same Stage
  .github/workflows/image.yml
Labels: bug

#44 Also tag dev on Release
  tasks/utils.py
Labels: bug

#46 Use Leader Election for Provisioner & Resizer
  deploy/base/controller-statefulset.yaml
  deploy/base/daemonset.yaml
  deploy/base/kustomization.yaml
  deploy/base/node-rbac.yaml
  deploy/base/rbac.yaml
  deploy/overlays/dev/uselocalimage.yaml
  deploy/overlays/stable-gke/kustomization.yaml
  deploy/overlays/stable/kustomization.yaml
Labels: enhancement

#49 Remove UPX
  .github/workflows/image.yml
  Dockerfile
  dev-env.Dockerfile
  tasks/image.py
Labels: bug

#50 add container resources and raise priority
  deploy/base/daemonset.yaml
  docs/getting_started.md
Labels: documentation, enhancement

#52 Fix Sanity Tests
  .github/workflows/test.yml
  go.mod
  go.sum
  pkg/driver/node.go
Labels: bug

#54 Add ownerReferences to PublishedVolume
  pkg/util/common.go
Labels: enhancement
