Repository ofek/csi-gcs, pull requests merged in 2020-04, with the labels that each got.

#9 Sanity Tests
  .github/workflows/test.yml
  .gitignore
  Dockerfile
  csi_gcs_suite_test.go
  docs/contributing/setup.md
  go.mod
  go.sum
  pkg/driver/driver.go
  pkg/driver/mounter.go
  pkg/driver/node.go
  pkg/util/common.go
  tasks/__init__.py
  tasks/test.py
  test/.gitkeep
Labels: enhancement

#16 Support Manual Bucket Name in Dynamic Provisioner
  docs/dynamic_provisioning.md
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/util/common.go
Labels: enhancement

#20 update docs
  docs/contributing/authors.md
  docs/dynamic_provisioning.md
Labels: documentation, enhancement

#24 Flag Docs
  docs/_snippets/links.txt
  docs/dynamic_provisioning.md
  docs/static_provisioning.md
Labels: documentation, enhancement

#23 Stream gcsfuse Output to Logger
  pkg/driver/mounter.go
Labels: enhancement

#26 update flag docs
  docs/dynamic_provisioning.md
  docs/static_provisioning.md
Labels: documentation

#27 Development & CI Improvements
  .github/workflows/docs.yml
  .github/workflows/image.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .gitignore
  Dockerfile
  README.md
  bin/.gitkeep
  cmd/main.go
  dev-env.Dockerfile
  docs/contributing/setup.md
  docs/index.md
  go.mod
  go.sum
  pkg/driver/driver.go
  tasks/__init__.py
  tasks/build.py
  tasks/constants.py
  tasks/docs.py
  tasks/env.py
  tasks/image.py
  tasks/test.py
  tasks/utils.py
  test/sanity_test.go
Labels: enhancement

#30 Use new docs extension to guarantee global refs are always available
  docs/dynamic_provisioning.md
  docs/getting_started.md
  docs/index.md
  docs/static_provisioning.md
  mkdocs.yml
  tox.ini
Labels: documentation

#32 Support Volume Expansion
  deploy/base/controller-rbac.yaml
  deploy/base/controller-statefulset.yaml
  docs/csi_compatibility.md
  docs/dynamic_provisioning.md
  examples/dynamic/sc.yaml
  mkdocs.yml
  pkg/driver/controller.go
  pkg/driver/node.go
  pkg/util/common.go
Labels: documentation, enhancement
